### PR TITLE
Non-strict JSON parser

### LINKED ISSUE #383: JSON "parser" and colons
```
./vendor/bin/phpbench show latest --report='generator: "table", compare: "subject", compare_fields:[ "mode"], break: ["revs"], cols: ["benchmark"], sort: {"subject:benchGetOptimized:mode": "asc"}'

                                                                          
  [Seld\JsonLint\ParsingException]                                        
  Parse error on line 1:                                                  
  ... "sort": {"subject":benchGetOptimized:mo                             
  ----------------------^                                                 
  Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['  
                                                                          
```

Should not preifix replace `:` with `"` when inside of a quote.

### PR DESCRIPTION
**Pull request by dantleech**
Introduces a JSON normalizer for "non-strict" JSON, replacing the original and flawed `preg_replace`.

Fixes #383

### CODE REVIEW

File: lib/Json/JsonDecoder.php [hunk 1]
```diff
@@ -47,28 +47,114 @@ public function decode($jsonString)
...
+
+        // if we were in a fake quote and hit the end, then add the closing quote
+        if ($inFakeQuote) {
+            $chars[] = '"';
+        }
+
+        $normalized = implode('', $chars);
+
+        // if we added a bracket at the begining, then add one to the end if required
+        if (substr_count($normalized, '{') == substr_count($normalized, '}') + 1) {
```
Comment (dantleech) [inline lib/Json/JsonDecoder.php]: thats not going to work for quoted `{` characters
